approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:

    -
        name: admin
        required: 1
        members:
            - carlossuperlogica
            - luiscera
            - jhoncf
            - jeanrodrigues
            - matheusmazzola
