approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
 -   
  name: admin  
  members:  
  - carlossuperlogica
  - luiscera
  - jhoncf
  - jeanrodrigues
  - matheusmazzola
  required: 1
  conditions:
    files:
     - '*.*'
